[package]
name = "pc-manager-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "pc_manager_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
app-manager-client = { path = "../../../crates/app-manager-client" }
pc-core = { path = "../../../crates/pc-core" }
pc-monitor = { path = "../../../crates/pc-monitor" }
pc-windows = { path = "../../../crates/pc-windows" }
serde.workspace = true
serde_json = "1"
tauri = { version = "2", features = [] }
